# Generated by Django 4.2.2 on 2024-07-09 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="почта"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="комментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст рассылки")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Send",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_and_time_of_first_send",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "каждый день"),
                            ("weekly", "каждую неделю"),
                            ("monthly", "каждый месяц"),
                        ],
                        default="daily",
                        max_length=50,
                        verbose_name="Частота отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "создана"),
                            ("started", "запущена"),
                            ("finished", "закончена"),
                        ],
                        default="created",
                        max_length=50,
                        verbose_name="статус рассылки",
                    ),
                ),
                (
                    "client",
                    models.ManyToManyField(
                        related_name="mailings",
                        to="message.client",
                        verbose_name="Адрессаты",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                ("status", models.BooleanField(verbose_name="статус попытки")),
                (
                    "mail_answer",
                    models.TextField(verbose_name="ответ почтового сервера"),
                ),
                (
                    "send",
                    models.ForeignKey(
                        help_text="логгируемая рассылка",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_logs",
                        to="message.send",
                        verbose_name="логгируемая рассылка",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="message.message",
                verbose_name="сообщение",
            ),
        ),
    ]
